      IMPLICIT NONE

c---- Output information of the generators
      INTEGER    MXPART
      PARAMETER (MXPART=50)
      INTEGER NPART,NPARTGEN,PID,PIDGEN,KEEP,FLAG,MainDecay,UNIFORM
      REAL*8  P4INI,P4INIGEN,POL3INI
      COMMON/CMCINT/NPART,NPARTGEN,MainDecay,
     >              PID(MXPART),PIDGEN(MXPART),KEEP(MXPART),
     >              FLAG(MXPART),UNIFORM
      COMMON/CMCDOUBLE/P4INI(4,MXPART),
     >              P4INIGEN(4,MXPART),POL3INI(3,MXPART)

c---- PHOTOS common blocks
      INTEGER NMXHEP
      PARAMETER (NMXHEP=2000)
      INTEGER IDHEP,ISTHEP,JDAHEP,JMOHEP,NEVHEP,NHEP
      REAL*8 PHEP,VHEP
      COMMON/HEPEVT/NEVHEP,NHEP,ISTHEP(NMXHEP),IDHEP(NMXHEP),
     &JMOHEP(2,NMXHEP),JDAHEP(2,NMXHEP),PHEP(5,NMXHEP),VHEP(4,NMXHEP)

c---- Genbod common blocks
      INTEGER NP, KGENEV
      REAL    TECM, AMASS
      COMMON /GENIN / NP,TECM,AMASS(18),KGENEV
      REAL PCM, WT
      COMMON /GENOUT/ PCM(5,18),WT

c---- other
      INTEGER JKAON, MCADD4, MCADD4POL3, MCADD4GEN

