#  To suppress the instantiation of vis manager (G4VisExecutive), by
#  setting G4VIS_NONE, recompile pienu.cc and ensure drawing code is
#  executed only if G4VVisManager::GetConcreteInstance() is non-zero.
#

# /process/em/verbose 2
# /process/inactivate msc

# /decay/external # Call external decay generator
# /radiative/mu_or_e 0 # choose pi->e nu (g)


/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/event/printModulo 1000 #printout counter
/rndm/autoSeed true

#Commands for the pileup
/pileup/Active 0
/pileup/Rate 80000
/pileup/Tmin -20000
/pileup/Tmax 5000

# beam from Luca's approximation of the data
# /beam/FromData 7 #-> 2012 data in new primary gen action

#for positron gun
/gun/energy 70.0 # in MeV units 
/gun/angle 27.848 # in degree units -> R=30 mm

# prints out all processes defined in the physics list
# /run/particle/dumpOrderingParam

#Number of events to simulate
# /run/beamOn 600000 
/run/beamOn 5000
